name: practicalgitops.staging.infra

on:
  push:
    branches:
      - main
    paths:
      - "envs/**"
      - "infra/**"
  pull_request:
    branches:
      - main
    paths:
      - "envs/**"
      - "infra/**"

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    steps:
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_IAM_GITHUB_ACTION }}
          aws-region: "us-east-1"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Uncomment Terraform Cloud Backend Configuration file
        id: uncomment
        run: sed -i 's/^#*//' infra/backend.tf

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.3
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN_STAGING }}

      - name: Terraform Init
        id: init
        run: |
          echo -e "access_key = \"${AWS_ACCESS_KEY_ID}\"\nsecret_key = \"${AWS_SECRET_ACCESS_KEY}\"\ntoken = \"${AWS_SESSION_TOKEN}\"\nregion = \"${AWS_REGION:-${AWS_DEFAULT_REGION}}\"" | tee secret.tfvars
          terraform init -backend-config=envs/staging.hcl

      - name: Terraform Format
        id: format
        run: |
          terraform fmt *.tfvars
          terraform fmt -check

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        if: github.event_name == 'pull_request'
        with:
          directory: infra/
          quiet: true
          soft_fail: true
          framework: terraform
          output_format: cli
        continue-on-error: true

      - name: Checkov Results
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          CHECKOV: "checkov\n${{ env.CHECKOV_RESULTS }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `## Checkov Results
            <details><summary>Show Checkov Results</summary>
            ${process.env.CHECKOV}
            </details>
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
            github.rest.issues.createComment ({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color
        continue-on-error: true

      - name: Terraform Plan Output
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `## Terraform Staging Infra Plan

            #### Terraform Initialization \`${{ steps.init.outcome }}\`
            #### Terraform Validation \`${{ steps.validate.outcome }}\`
            #### Terraform Plan \`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>
            ${process.env.PLAN}
            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
            
            github.rest.issues.createComment ({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        if: github.ref == 'refs/heads/staging' && github.event_name == 'push'
        run: terraform apply